name: "Test"
on:
  push:
    branches:
      - master

jobs:
  Mydra:
    runs-on: ubuntu-20.04
    steps:

    # Installation
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true

        - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

        - name: Build
      run: |
        nix-build -E "with import <nixpkgs> {}; callPackage ./default.nix {}"

        - name: Test
      run: |
        ./test.sh